name: Update Static Files

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 6'

jobs:
  UpdateData:
    name: Update All Static Files
    runs-on: ubuntu-latest
    env:
      GITHUB_USER: github-actions[bot]
      GITHUB_EMAIL: 41898282+github-actions[bot]@users.noreply.github.com
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout Project
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.SKYRA_TOKEN }}
      - name: Use Node.js v18
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn
      - name: Install Dependencies
        run: yarn --immutable

      - name: Configure git
        run: |
          git remote set-url origin "https://${GITHUB_TOKEN}:x-oauth-basic@github.com/${GITHUB_REPOSITORY}.git";
          git config --local user.email "${GITHUB_EMAIL}";
          git config --local user.name "${GITHUB_USER}";

      - name: Run the Emoji Extraction script
        run: node ./scripts/extract-emoji-data.mjs
      - name: Commit emoji data changes and push
        run: |
          git add .;
          if git diff-index --quiet HEAD --; then
            echo "No emoji changes to commit"
          else
            git commit -sam "refactor: update emoji data";
            git push --set-upstream origin $(git rev-parse --abbrev-ref HEAD);
          fi

      - name: Run the Unicode Extraction script
        run: node ./scripts/extract-unicode-data.mjs
      - name: Commit unicode data changes and push
        run: |
          git add .;
          if git diff-index --quiet HEAD --; then
            echo "No unicode changes to commit"
          else
            git commit -sam "refactor: update unicode data";
            git push --set-upstream origin $(git rev-parse --abbrev-ref HEAD);
          fi

      - name: Run the Timezone Extraction script
        run: node ./scripts/extract-timezone-data.mjs
      - name: Commit timezone data changes and push
        run: |
          git add .;
          if git diff-index --quiet HEAD --; then
            echo "No timezone changes to commit"
          else
            git commit -sam "refactor: update timezones data";
            git push --set-upstream origin $(git rev-parse --abbrev-ref HEAD);
          fi
